- name: Example playbook for Windows
  hosts: "{{ host }}"
  gather_facts: no

  tasks:
    - name: "Fail if Extra Variable {{ host }} does not exist in Ansible Tower's inventory"
      fail:
        msg: "{{ item }} does not exist in Ansible Tower's inventory."
        when: "item not in groups['all']" 
        with_items: "{{host}}"
      rescue:
      - name: Failure to get host in tower inventory
        debug:
          msg: "SYNTBOT_OUTPUT: FAILED:  Task to Check if hosts exists in tower  failed on {{ host }}: Failed to find hosts in Ansible tower inventory "
        failed_when: True


    - name: Run some task on Windows
      win_service:
        name: spooler
        state: started


