---
- name: Execute PowerShell Script
  hosts: "{{ host }}"
  gather_facts: no  # Disable fact gathering for Windows hosts

  tasks:
    - name: Execute the PowerShell script
      win_command: powershell.exe -ExecutionPolicy Bypass -File "C:\PrePostChecks-without-BIB\MasterBots\Masterbot-WindowsHealthChecks.ps1"
      register: output

    - name: print the output
      debug:
        var: output.stdout

    - name: Parse HTML file path
      set_fact:
        html_file_path: "{{ output.stdout | regex_search('html path is (.+)', '\\1') }}"
      vars:
        output: "{{ output.stdout }}"
  
    - name: Print HTML file path
      debug:
        var: html_file_path
