---
- name: install maven
  hosts: client2
  become: true

  tasks:
  - name: Get update
    apt:
    update_cache: true
    
       

  tasks:
  - name: Install OpenJDK
    apt:
      name: openjdk-11-jre-headless

  - name: download apache maven
    get_url:
      url: https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      dest: /opt

  - name: extract maven packages
    unarchive:
      src: /opt/apache-maven-3.6.3-bin.tar.gz
      dest: /opt
      remote_src: yes
   
   - name: renaming maven
     command: mv apache-maven-3.6.3 apachemaven
     
     - name: Update hosts
       lineinfile:
         path: /etc/hosts
         state: present
         line: "{{ item }}"
       with_items:
  - '192.168.0.108 K8_slave'
  - '192.168.0.105 K8_master
     
  
