- name: Install apt using task
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Fetch AWS Credentials from Ansible Tower
      set_fact:
        aws_credentials: "{{ lookup('tower_credential', 'credential_id', '16') }}"
      no_log: true


    - name: Print AWS Credentials
      debug:
        var: aws_credentials
