---
- name: Install apache2 
  hosts: 16.170.246.141
  remote_user: ubuntu
  gather_facts: yes 


  tasks:
    - name: Install Apache service 
      apt:
        name: apache2
        state: present 
