---
- name: Install apache2 
  hosts: all
  remote_user: root
  become: yes
  gather_facts: yes 


  tasks:
    - name: Install Apache service 
      apt:
        name: apache2
        state: present 
