--- #playbook to insattl YUM package in target host
- name: Install apt using task 
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: print msg
      debug:
        msg: "Hello world"
        

