--- #playbook to insattl YUM package in target host
- name: Install apt using task 
  hosts: localhost
  remote_user: root
  become: yes
  gather_facts: yes

  tasks:
    - name: print msg
      debug:
        msg: "Hello world"
        
    - name: get user id
      debug:
        msg: "{{ ansible_user_id }}"

    - name: print pwd
      command: pwd
      register: pwdResult

    - name: print pwd result
      debug:
        var: pwdResult

 

    - name: Execute Python script through shell module
      shell: python3 /var/lib/awx/projects/rinki/test.py
      delegate_to: 35.154.24.128
      

    - name: python script
      command: python3 /var/lib/awx/projects/rinki/test.py
      register: result

    - name: print result
      debug:
        var: result 

        

