--- #playbook to insattl YUM package in target host
- name: Install apt using task 
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: print msg
      debug:
        msg: "Hello world"
        
    - name: get user id
      debug:
        msg: "{{ ansible_user_id }}"

    - name: print pwd
      command: pwd
      register: pwdResult

    - name: print pwd result
      debug:
        var: pwdResult

    - name: Copy file to /runner/project
      copy:
        src: /var/lib/awx/projects/rinki/test.py
        dest: /runner/project/test.py

    - name: Show the file permissions
      shell: ls -l /runner/project/test.py
      register: file_permissions_output
      changed_when: false
      ignore_errors: yes

 

    - name: Execute Python script through shell module
      shell: python3 /runner/project/test.py
      

    - name: python script
      command: "python3 /runner/project/test.py"
      register: result

    - name: print result
      debug:
        var: result 

        

