- name: hitting Data from MySQL
  hosts: localhost

  vars:
    host: "db.vishal-chauhan.in"
    #host: "194.195.112.205:30517"
  tasks:
    - name: Update apt cache
      yum:
        update_cache: yes
      tags: update

    - name: Install python3-devel, mysql-devel, and make
      dnf:
        name: ['python3-devel', 'mysql-devel', 'make']
        state: latest
      tags: install

    - name: Install mysqlclient
      pip:
        name: mysqlclient
        state: present

    - name: Execute MySQL Query
      community.mysql.mysql_query:
        login_host: "{{ host }}"
        login_user: "linroot"
        #login_user: "root"
        login_password: "&rU1HRBh4W9UHkDb"
        #login_password: "IRONMAN"
        login_db: Ansible
        query: SELECT * FROM Ansible.cmdb_ci;
      register: query_result

    - name: Debug Query Result
      debug:
        var: query_result
