---
- name: Reading csv information
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Install apt package
      community.general.read_csv:
        path: samplecsv.csv
      register: usecase

    - name: Print usecase name and value 
      debug:
        msg: "{{ usecase }}"
