- name: hitting Data from MySQL
  hosts: localhost


  tasks:
    # - name: print username
    #   set_fact:
    #     host: "{{ var_db_hostname }}"
    #     password: "{{ var_db_password }}"
    #     user: "{{var_db_username }}"

    - name: Execute MySQL Query
      community.mysql.mysql_query:
        login_host: "{{ var_db_hostname }}"
        login_user: "{{ var_db_username }}"
        login_port: "30517"
       
        login_password: "{{ var_db_password }}"

        login_db: cat
        query: "SELECT * FROM `cat-table`;"
      register: query_result

    - name: Debug Query Result
      debug:
        var: query_result
