- name: hitting Data from MySQL
  hosts: localhost


  tasks:
    - name: Execute MySQL Query
      community.mysql.mysql_query:
        login_host: "{{ var_db_hostname }}"
        login_user: "{{ var_db_username }}"
        login_port: "{{ var_db_port }}"
       
        login_password: "{{ var_db_password }}"

        login_db: cat
        query: "SELECT * FROM `incidentdata.ci_details`;"
      register: query_result

    - name: Debug Query Result
      debug:
        var: query_result
