---
- name: stop service
  hosts: "{{ host }}"
  remote_user: root
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:
    - name: Stop Apache Service
      service:
        name: apache2
        state: stopped
